export * from './enderecopage'
export * from './feedpage'
export * from './loginpage'
export * from './homepage'
export * from './restaurantpage'
export * from './searchpage'
export * from './signuppage'